### ISSUE TITLE
The passed in AttributeData to GenerateAsync never contains attribute arguments

### ISSUE THREAD

**Issue by theresia-tobii** [cezarypiatek/SmartCodeGenerator#1]
I have successfully been able to create a generator based on this project and I think it is much better than the CodeGeneration.Roslyn project. However I did run into one issue. When using a marker attribute with arguments, those arguments can not be accessed in the generator. I did some investigation and found that both SmartCodeGenerator and CodeGeneration.Roslyn use CSharpCompilation.Assembly.GetAttributes to access for example assembly level attributes. Using CodeGeneration.Roslyn the compilation gives attributes with correct data but SmartCodeGenerator does not. I traced back some more and noticed that the compilations are created in completely different ways. Maybe that has something to do with it?

I am able to "hack" around this by extracting the attribute data manually from the syntax tree but that's very cumbersome and error-prone to parse it like that. Would be great if you could have a look, seeing as you're the expert here and it seems like the API should be providing this in the markerAttribute parameter to GenerateAsync.

**Comment by cezarypiatek** [comment]
Hi, 
You should get all the data about the marker attribute within `AttributeData markerAttribute` parameter.
I've recently observed that there are sometimes issues with loading semantic data cause by the reference to netstandard.netcore projects. A similar issue is reported here https://github.com/cezarypiatek/MappingGenerator/issues/104

I'm using MSBuildWorkspace to load project data (this was taken from the official example for roslyn CLI tools)  instead of building compilation manually (like CodeGeneration.Roslyn do). I've tried to replace this component with https://github.com/daveaglick/Buildalyzer but I hit a similar issue and I haven't got any response about it https://github.com/daveaglick/Buildalyzer/issues/130

Can you provide more details that could possibly help me investigate this issue?
- Example of your attribute with parameters
- The level at which the attribute is applied? (assembly, type, etc)

Update:

I'm trying to reach @daveaglick (the maintainer of Buildalyzer ) via Twitter, I hope he could help me.

**Comment by daveaglick** [comment]
I'm around! :smile: Things have been a little crazy for me (and everyone else) lately so I'm running a little behind on OSS issues. I'll try to follow-up on the Buildalyzer issue this week.

**Comment by cezarypiatek** [comment]
@theresia-tobii this should be solved by #4  
Can you update SmartCodeGenerator.Engine nuget package and test the new version and let me know if it works?
